name: Comment Lint Results

permissions:
  checks: write
  pull-requests: write

on:
  workflow_run:
    workflows: ["lint"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.14.0 # v0.17  buggy
        with:
          lgtm_comment_body: 'All checks passed. Good job! 👍'
          annotations: false
          max_comments: 10
