name: SocketWire Lint

on:
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.clang-format'
      - '**.clang-tidy'

permissions:
  contents: read

jobs:
  check-format-and-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '19'
        fallback-style: 'none'

    - uses: ZedThree/clang-tidy-review@v0.14.0 # v0.17 was buggy
      id: review
      with:
        apt_packages: 'libx11-dev'
        build_dir: build
        cmake_command: cmake -Bbuild -S. -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        clang_tidy_checks: '' # Use closest .clang-tidy config, not some weird default
        split_workflow: true # So that comments work with fork PRs

    # Upload review results as artifacts, a different workflow posts them
    # as comments. This is required due to security stuff.
    - uses: ZedThree/clang-tidy-review/upload@v0.14.0 # v0.17 is buggy
